sonar.projectKey=vinialexandre_psw-digital-fullstack-challenge
sonar.organization=vinialexandre

sonar.projectName=PSW Digital Fullstack Challenge
sonar.projectVersion=1.0

sonar.sources=app,components,hooks,lib,types

sonar.tests=__tests__

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/jest.config.js,**/jest.setup.js,**/*.d.ts

sonar.exclusions=node_modules/**,.next/**,coverage/**,out/**,public/**,*.config.js,*.config.ts,*.config.mjs

sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

