sonar.projectKey=vinialexandre_psw-digital-fullstack-challenge
sonar.organization=vinialexandre

sonar.projectName=PSW Digital Fullstack Challenge
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.language=cs

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx

sonar.coverage.exclusions=**/Program.cs,**/Migrations/**,**/*Dto.cs,**/*Request.cs,**/*Response.cs

sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**

sonar.dotnet.excludeTestProjects=true

