sonar.projectKey=vinialexandre_psw-digital-fullstack-challenge-backend
sonar.organization=vinialexandre

sonar.projectName=PSW Digital Fullstack Challenge - Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

sonar.coverage.exclusions=**/Program.cs,**/Migrations/**

sonar.exclusions=**/bin/**,**/obj/**,**/coverage/**

